// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bolg/v1/battle.proto

package bolg

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartBattleRequest struct {
	InitHp               int32    `protobuf:"varint,1,opt,name=init_hp,json=initHp,proto3" json:"init_hp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartBattleRequest) Reset()         { *m = StartBattleRequest{} }
func (m *StartBattleRequest) String() string { return proto.CompactTextString(m) }
func (*StartBattleRequest) ProtoMessage()    {}
func (*StartBattleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cedcb1bd8302cf06, []int{0}
}

func (m *StartBattleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartBattleRequest.Unmarshal(m, b)
}
func (m *StartBattleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartBattleRequest.Marshal(b, m, deterministic)
}
func (m *StartBattleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartBattleRequest.Merge(m, src)
}
func (m *StartBattleRequest) XXX_Size() int {
	return xxx_messageInfo_StartBattleRequest.Size(m)
}
func (m *StartBattleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartBattleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartBattleRequest proto.InternalMessageInfo

func (m *StartBattleRequest) GetInitHp() int32 {
	if m != nil {
		return m.InitHp
	}
	return 0
}

// Goole API doc: https://cloud.google.com/apis/design/design_patterns?hl=ja
// カスタム メソッドでは、空の場合でも独自の XxxResponse メッセージが返されることが推奨されます。
// メソッドの機能が時間とともに拡張し、追加のデータを返さなければならなくなる可能性が高まるためです。
type StartBattleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartBattleResponse) Reset()         { *m = StartBattleResponse{} }
func (m *StartBattleResponse) String() string { return proto.CompactTextString(m) }
func (*StartBattleResponse) ProtoMessage()    {}
func (*StartBattleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cedcb1bd8302cf06, []int{1}
}

func (m *StartBattleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartBattleResponse.Unmarshal(m, b)
}
func (m *StartBattleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartBattleResponse.Marshal(b, m, deterministic)
}
func (m *StartBattleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartBattleResponse.Merge(m, src)
}
func (m *StartBattleResponse) XXX_Size() int {
	return xxx_messageInfo_StartBattleResponse.Size(m)
}
func (m *StartBattleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartBattleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartBattleResponse proto.InternalMessageInfo

type StopBattleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopBattleResponse) Reset()         { *m = StopBattleResponse{} }
func (m *StopBattleResponse) String() string { return proto.CompactTextString(m) }
func (*StopBattleResponse) ProtoMessage()    {}
func (*StopBattleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cedcb1bd8302cf06, []int{2}
}

func (m *StopBattleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopBattleResponse.Unmarshal(m, b)
}
func (m *StopBattleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopBattleResponse.Marshal(b, m, deterministic)
}
func (m *StopBattleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopBattleResponse.Merge(m, src)
}
func (m *StopBattleResponse) XXX_Size() int {
	return xxx_messageInfo_StopBattleResponse.Size(m)
}
func (m *StopBattleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopBattleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopBattleResponse proto.InternalMessageInfo

type NotifyHitRequest struct {
	// 受信したIR-ID
	IrId                 int32    `protobuf:"varint,1,opt,name=ir_id,json=irId,proto3" json:"ir_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyHitRequest) Reset()         { *m = NotifyHitRequest{} }
func (m *NotifyHitRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyHitRequest) ProtoMessage()    {}
func (*NotifyHitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cedcb1bd8302cf06, []int{3}
}

func (m *NotifyHitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyHitRequest.Unmarshal(m, b)
}
func (m *NotifyHitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyHitRequest.Marshal(b, m, deterministic)
}
func (m *NotifyHitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyHitRequest.Merge(m, src)
}
func (m *NotifyHitRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyHitRequest.Size(m)
}
func (m *NotifyHitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyHitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyHitRequest proto.InternalMessageInfo

func (m *NotifyHitRequest) GetIrId() int32 {
	if m != nil {
		return m.IrId
	}
	return 0
}

type NotifyHitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyHitResponse) Reset()         { *m = NotifyHitResponse{} }
func (m *NotifyHitResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyHitResponse) ProtoMessage()    {}
func (*NotifyHitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cedcb1bd8302cf06, []int{4}
}

func (m *NotifyHitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyHitResponse.Unmarshal(m, b)
}
func (m *NotifyHitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyHitResponse.Marshal(b, m, deterministic)
}
func (m *NotifyHitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyHitResponse.Merge(m, src)
}
func (m *NotifyHitResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyHitResponse.Size(m)
}
func (m *NotifyHitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyHitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyHitResponse proto.InternalMessageInfo

type EventResult struct {
	// Types that are valid to be assigned to Type:
	//	*EventResult_JoinRoom_
	//	*EventResult_LeaveRoom_
	//	*EventResult_CreateBattle
	//	*EventResult_DeleteBattle
	//	*EventResult_Death_
	//	*EventResult_EndBattle_
	Type                 isEventResult_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EventResult) Reset()         { *m = EventResult{} }
func (m *EventResult) String() string { return proto.CompactTextString(m) }
func (*EventResult) ProtoMessage()    {}
func (*EventResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_cedcb1bd8302cf06, []int{5}
}

func (m *EventResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResult.Unmarshal(m, b)
}
func (m *EventResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResult.Marshal(b, m, deterministic)
}
func (m *EventResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResult.Merge(m, src)
}
func (m *EventResult) XXX_Size() int {
	return xxx_messageInfo_EventResult.Size(m)
}
func (m *EventResult) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResult.DiscardUnknown(m)
}

var xxx_messageInfo_EventResult proto.InternalMessageInfo

type isEventResult_Type interface {
	isEventResult_Type()
}

type EventResult_JoinRoom_ struct {
	JoinRoom *EventResult_JoinRoom `protobuf:"bytes,1,opt,name=join_room,json=joinRoom,proto3,oneof"`
}

type EventResult_LeaveRoom_ struct {
	LeaveRoom *EventResult_LeaveRoom `protobuf:"bytes,6,opt,name=leave_room,json=leaveRoom,proto3,oneof"`
}

type EventResult_CreateBattle struct {
	CreateBattle *EventResult_StartBattle `protobuf:"bytes,2,opt,name=create_battle,json=createBattle,proto3,oneof"`
}

type EventResult_DeleteBattle struct {
	DeleteBattle *EventResult_StopBattle `protobuf:"bytes,3,opt,name=delete_battle,json=deleteBattle,proto3,oneof"`
}

type EventResult_Death_ struct {
	Death *EventResult_Death `protobuf:"bytes,4,opt,name=death,proto3,oneof"`
}

type EventResult_EndBattle_ struct {
	EndBattle *EventResult_EndBattle `protobuf:"bytes,5,opt,name=end_battle,json=endBattle,proto3,oneof"`
}

func (*EventResult_JoinRoom_) isEventResult_Type() {}

func (*EventResult_LeaveRoom_) isEventResult_Type() {}

func (*EventResult_CreateBattle) isEventResult_Type() {}

func (*EventResult_DeleteBattle) isEventResult_Type() {}

func (*EventResult_Death_) isEventResult_Type() {}

func (*EventResult_EndBattle_) isEventResult_Type() {}

func (m *EventResult) GetType() isEventResult_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *EventResult) GetJoinRoom() *EventResult_JoinRoom {
	if x, ok := m.GetType().(*EventResult_JoinRoom_); ok {
		return x.JoinRoom
	}
	return nil
}

func (m *EventResult) GetLeaveRoom() *EventResult_LeaveRoom {
	if x, ok := m.GetType().(*EventResult_LeaveRoom_); ok {
		return x.LeaveRoom
	}
	return nil
}

func (m *EventResult) GetCreateBattle() *EventResult_StartBattle {
	if x, ok := m.GetType().(*EventResult_CreateBattle); ok {
		return x.CreateBattle
	}
	return nil
}

func (m *EventResult) GetDeleteBattle() *EventResult_StopBattle {
	if x, ok := m.GetType().(*EventResult_DeleteBattle); ok {
		return x.DeleteBattle
	}
	return nil
}

func (m *EventResult) GetDeath() *EventResult_Death {
	if x, ok := m.GetType().(*EventResult_Death_); ok {
		return x.Death
	}
	return nil
}

func (m *EventResult) GetEndBattle() *EventResult_EndBattle {
	if x, ok := m.GetType().(*EventResult_EndBattle_); ok {
		return x.EndBattle
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EventResult) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EventResult_JoinRoom_)(nil),
		(*EventResult_LeaveRoom_)(nil),
		(*EventResult_CreateBattle)(nil),
		(*EventResult_DeleteBattle)(nil),
		(*EventResult_Death_)(nil),
		(*EventResult_EndBattle_)(nil),
	}
}

type EventResult_JoinRoom struct {
	PlayerName           string   `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	PlayerHp             string   `protobuf:"bytes,2,opt,name=player_hp,json=playerHp,proto3" json:"player_hp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResult_JoinRoom) Reset()         { *m = EventResult_JoinRoom{} }
func (m *EventResult_JoinRoom) String() string { return proto.CompactTextString(m) }
func (*EventResult_JoinRoom) ProtoMessage()    {}
func (*EventResult_JoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_cedcb1bd8302cf06, []int{5, 0}
}

func (m *EventResult_JoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResult_JoinRoom.Unmarshal(m, b)
}
func (m *EventResult_JoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResult_JoinRoom.Marshal(b, m, deterministic)
}
func (m *EventResult_JoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResult_JoinRoom.Merge(m, src)
}
func (m *EventResult_JoinRoom) XXX_Size() int {
	return xxx_messageInfo_EventResult_JoinRoom.Size(m)
}
func (m *EventResult_JoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResult_JoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_EventResult_JoinRoom proto.InternalMessageInfo

func (m *EventResult_JoinRoom) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *EventResult_JoinRoom) GetPlayerHp() string {
	if m != nil {
		return m.PlayerHp
	}
	return ""
}

type EventResult_LeaveRoom struct {
	PlayerName           string   `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResult_LeaveRoom) Reset()         { *m = EventResult_LeaveRoom{} }
func (m *EventResult_LeaveRoom) String() string { return proto.CompactTextString(m) }
func (*EventResult_LeaveRoom) ProtoMessage()    {}
func (*EventResult_LeaveRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_cedcb1bd8302cf06, []int{5, 1}
}

func (m *EventResult_LeaveRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResult_LeaveRoom.Unmarshal(m, b)
}
func (m *EventResult_LeaveRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResult_LeaveRoom.Marshal(b, m, deterministic)
}
func (m *EventResult_LeaveRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResult_LeaveRoom.Merge(m, src)
}
func (m *EventResult_LeaveRoom) XXX_Size() int {
	return xxx_messageInfo_EventResult_LeaveRoom.Size(m)
}
func (m *EventResult_LeaveRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResult_LeaveRoom.DiscardUnknown(m)
}

var xxx_messageInfo_EventResult_LeaveRoom proto.InternalMessageInfo

func (m *EventResult_LeaveRoom) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

type EventResult_StartBattle struct {
	InitHp               int32    `protobuf:"varint,1,opt,name=init_hp,json=initHp,proto3" json:"init_hp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResult_StartBattle) Reset()         { *m = EventResult_StartBattle{} }
func (m *EventResult_StartBattle) String() string { return proto.CompactTextString(m) }
func (*EventResult_StartBattle) ProtoMessage()    {}
func (*EventResult_StartBattle) Descriptor() ([]byte, []int) {
	return fileDescriptor_cedcb1bd8302cf06, []int{5, 2}
}

func (m *EventResult_StartBattle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResult_StartBattle.Unmarshal(m, b)
}
func (m *EventResult_StartBattle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResult_StartBattle.Marshal(b, m, deterministic)
}
func (m *EventResult_StartBattle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResult_StartBattle.Merge(m, src)
}
func (m *EventResult_StartBattle) XXX_Size() int {
	return xxx_messageInfo_EventResult_StartBattle.Size(m)
}
func (m *EventResult_StartBattle) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResult_StartBattle.DiscardUnknown(m)
}

var xxx_messageInfo_EventResult_StartBattle proto.InternalMessageInfo

func (m *EventResult_StartBattle) GetInitHp() int32 {
	if m != nil {
		return m.InitHp
	}
	return 0
}

type EventResult_StopBattle struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResult_StopBattle) Reset()         { *m = EventResult_StopBattle{} }
func (m *EventResult_StopBattle) String() string { return proto.CompactTextString(m) }
func (*EventResult_StopBattle) ProtoMessage()    {}
func (*EventResult_StopBattle) Descriptor() ([]byte, []int) {
	return fileDescriptor_cedcb1bd8302cf06, []int{5, 3}
}

func (m *EventResult_StopBattle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResult_StopBattle.Unmarshal(m, b)
}
func (m *EventResult_StopBattle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResult_StopBattle.Marshal(b, m, deterministic)
}
func (m *EventResult_StopBattle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResult_StopBattle.Merge(m, src)
}
func (m *EventResult_StopBattle) XXX_Size() int {
	return xxx_messageInfo_EventResult_StopBattle.Size(m)
}
func (m *EventResult_StopBattle) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResult_StopBattle.DiscardUnknown(m)
}

var xxx_messageInfo_EventResult_StopBattle proto.InternalMessageInfo

type EventResult_Death struct {
	KillPlayerName       string   `protobuf:"bytes,1,opt,name=kill_player_name,json=killPlayerName,proto3" json:"kill_player_name,omitempty"`
	DeathPlayerName      string   `protobuf:"bytes,2,opt,name=death_player_name,json=deathPlayerName,proto3" json:"death_player_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResult_Death) Reset()         { *m = EventResult_Death{} }
func (m *EventResult_Death) String() string { return proto.CompactTextString(m) }
func (*EventResult_Death) ProtoMessage()    {}
func (*EventResult_Death) Descriptor() ([]byte, []int) {
	return fileDescriptor_cedcb1bd8302cf06, []int{5, 4}
}

func (m *EventResult_Death) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResult_Death.Unmarshal(m, b)
}
func (m *EventResult_Death) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResult_Death.Marshal(b, m, deterministic)
}
func (m *EventResult_Death) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResult_Death.Merge(m, src)
}
func (m *EventResult_Death) XXX_Size() int {
	return xxx_messageInfo_EventResult_Death.Size(m)
}
func (m *EventResult_Death) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResult_Death.DiscardUnknown(m)
}

var xxx_messageInfo_EventResult_Death proto.InternalMessageInfo

func (m *EventResult_Death) GetKillPlayerName() string {
	if m != nil {
		return m.KillPlayerName
	}
	return ""
}

func (m *EventResult_Death) GetDeathPlayerName() string {
	if m != nil {
		return m.DeathPlayerName
	}
	return ""
}

// バトルが終了した場合に返ってくる
type EventResult_EndBattle struct {
	WinnerName           string   `protobuf:"bytes,1,opt,name=winner_name,json=winnerName,proto3" json:"winner_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResult_EndBattle) Reset()         { *m = EventResult_EndBattle{} }
func (m *EventResult_EndBattle) String() string { return proto.CompactTextString(m) }
func (*EventResult_EndBattle) ProtoMessage()    {}
func (*EventResult_EndBattle) Descriptor() ([]byte, []int) {
	return fileDescriptor_cedcb1bd8302cf06, []int{5, 5}
}

func (m *EventResult_EndBattle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResult_EndBattle.Unmarshal(m, b)
}
func (m *EventResult_EndBattle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResult_EndBattle.Marshal(b, m, deterministic)
}
func (m *EventResult_EndBattle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResult_EndBattle.Merge(m, src)
}
func (m *EventResult_EndBattle) XXX_Size() int {
	return xxx_messageInfo_EventResult_EndBattle.Size(m)
}
func (m *EventResult_EndBattle) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResult_EndBattle.DiscardUnknown(m)
}

var xxx_messageInfo_EventResult_EndBattle proto.InternalMessageInfo

func (m *EventResult_EndBattle) GetWinnerName() string {
	if m != nil {
		return m.WinnerName
	}
	return ""
}

func init() {
	proto.RegisterType((*StartBattleRequest)(nil), "bolg.v1.StartBattleRequest")
	proto.RegisterType((*StartBattleResponse)(nil), "bolg.v1.StartBattleResponse")
	proto.RegisterType((*StopBattleResponse)(nil), "bolg.v1.StopBattleResponse")
	proto.RegisterType((*NotifyHitRequest)(nil), "bolg.v1.NotifyHitRequest")
	proto.RegisterType((*NotifyHitResponse)(nil), "bolg.v1.NotifyHitResponse")
	proto.RegisterType((*EventResult)(nil), "bolg.v1.EventResult")
	proto.RegisterType((*EventResult_JoinRoom)(nil), "bolg.v1.EventResult.JoinRoom")
	proto.RegisterType((*EventResult_LeaveRoom)(nil), "bolg.v1.EventResult.LeaveRoom")
	proto.RegisterType((*EventResult_StartBattle)(nil), "bolg.v1.EventResult.StartBattle")
	proto.RegisterType((*EventResult_StopBattle)(nil), "bolg.v1.EventResult.StopBattle")
	proto.RegisterType((*EventResult_Death)(nil), "bolg.v1.EventResult.Death")
	proto.RegisterType((*EventResult_EndBattle)(nil), "bolg.v1.EventResult.EndBattle")
}

func init() { proto.RegisterFile("bolg/v1/battle.proto", fileDescriptor_cedcb1bd8302cf06) }

var fileDescriptor_cedcb1bd8302cf06 = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x51, 0x53, 0xd3, 0x4c,
	0x14, 0x6d, 0xf9, 0x48, 0x21, 0xb7, 0xf4, 0x13, 0x16, 0x14, 0x0c, 0x2a, 0x4c, 0x1f, 0x94, 0x71,
	0x24, 0x11, 0x7c, 0x94, 0x19, 0xc7, 0x0a, 0x12, 0x19, 0x86, 0x61, 0xc2, 0x9b, 0x33, 0x4e, 0x26,
	0x25, 0x97, 0x74, 0x31, 0xd9, 0x8d, 0xe9, 0x36, 0x4e, 0x7f, 0x92, 0x3f, 0xc8, 0xff, 0xe3, 0xec,
	0x6e, 0x92, 0x06, 0x48, 0xf5, 0xa9, 0xdd, 0xb3, 0xe7, 0x9c, 0x7b, 0xef, 0x49, 0x6e, 0x60, 0x63,
	0xc8, 0xe3, 0xc8, 0xc9, 0x0f, 0x9c, 0x61, 0x20, 0x44, 0x8c, 0x76, 0x9a, 0x71, 0xc1, 0xc9, 0x92,
	0x44, 0xed, 0xfc, 0xc0, 0xda, 0x8e, 0x38, 0x8f, 0x62, 0x74, 0x14, 0x3c, 0x9c, 0xdc, 0x38, 0x98,
	0xa4, 0x62, 0xaa, 0x59, 0xfd, 0x7d, 0x20, 0x57, 0x22, 0xc8, 0xc4, 0x40, 0x49, 0x3d, 0xfc, 0x31,
	0xc1, 0xb1, 0x20, 0x9b, 0xb0, 0x44, 0x19, 0x15, 0xfe, 0x28, 0xdd, 0x6a, 0xef, 0xb6, 0xf7, 0x0c,
	0xaf, 0x23, 0x8f, 0x6e, 0xda, 0x7f, 0x0c, 0xeb, 0x77, 0xe8, 0xe3, 0x94, 0xb3, 0x31, 0xf6, 0x37,
	0xa4, 0x0b, 0x4f, 0xef, 0xa1, 0xaf, 0x60, 0xf5, 0x82, 0x0b, 0x7a, 0x33, 0x75, 0xa9, 0x28, 0x9d,
	0xd7, 0xc1, 0xa0, 0x99, 0x4f, 0xc3, 0xc2, 0x77, 0x91, 0x66, 0x5f, 0xc2, 0xfe, 0x3a, 0xac, 0xd5,
	0x88, 0x85, 0xfa, 0xb7, 0x01, 0xdd, 0x93, 0x1c, 0x99, 0x44, 0x26, 0xb1, 0x20, 0x47, 0x60, 0xde,
	0x72, 0xca, 0xfc, 0x8c, 0xf3, 0x44, 0xa9, 0xbb, 0x87, 0xcf, 0xed, 0x62, 0x46, 0xbb, 0x46, 0xb4,
	0xcf, 0x38, 0x65, 0x1e, 0xe7, 0x89, 0xdb, 0xf2, 0x96, 0x6f, 0x8b, 0xff, 0xe4, 0x03, 0x40, 0x8c,
	0x41, 0x8e, 0x5a, 0xde, 0x51, 0xf2, 0x17, 0x8d, 0xf2, 0x73, 0x49, 0x2b, 0xf4, 0x66, 0x5c, 0x1e,
	0xc8, 0x29, 0xf4, 0xae, 0x33, 0x0c, 0x04, 0xfa, 0x3a, 0xe5, 0xad, 0x05, 0xe5, 0xb1, 0xdb, 0xe8,
	0x51, 0xcb, 0xc8, 0x6d, 0x79, 0x2b, 0x5a, 0xa8, 0xcf, 0xe4, 0x33, 0xf4, 0x42, 0x8c, 0x71, 0x66,
	0xf4, 0x9f, 0x32, 0xda, 0x99, 0x63, 0x54, 0xa6, 0x2a, 0x7d, 0xb4, 0xae, 0xf0, 0x39, 0x04, 0x23,
	0xc4, 0x40, 0x8c, 0xb6, 0x16, 0x95, 0xde, 0x6a, 0xd4, 0x1f, 0x4b, 0x86, 0xdb, 0xf2, 0x34, 0x55,
	0xa6, 0x80, 0x2c, 0x2c, 0x0b, 0x1b, 0x7f, 0x49, 0xe1, 0x84, 0x85, 0x55, 0x5d, 0x13, 0xcb, 0x83,
	0xe5, 0xc2, 0x72, 0x19, 0x2f, 0xd9, 0x81, 0x6e, 0x1a, 0x07, 0x53, 0xcc, 0x7c, 0x16, 0x24, 0xa8,
	0x1e, 0x89, 0xe9, 0x81, 0x86, 0x2e, 0x82, 0x04, 0xc9, 0x36, 0x98, 0x05, 0x61, 0x94, 0xaa, 0xb8,
	0x4c, 0x6f, 0x59, 0x03, 0x6e, 0x6a, 0xbd, 0x01, 0xb3, 0x4a, 0xfa, 0x9f, 0x56, 0xd6, 0x4b, 0xe8,
	0xd6, 0x32, 0x9d, 0xfb, 0x7e, 0x5a, 0x2b, 0x00, 0xb3, 0xc8, 0xac, 0x6f, 0x60, 0xa8, 0x00, 0xc8,
	0x1e, 0xac, 0x7e, 0xa7, 0x71, 0xec, 0x3f, 0x2c, 0xf2, 0xbf, 0xc4, 0x2f, 0x67, 0x3d, 0xbf, 0x86,
	0x35, 0x15, 0xd5, 0x1d, 0xaa, 0xee, 0xfd, 0x91, 0xba, 0x98, 0x71, 0xe5, 0x08, 0x55, 0x4c, 0x72,
	0x84, 0x9f, 0x94, 0xb1, 0x7b, 0x23, 0x68, 0x48, 0xb2, 0x07, 0x1d, 0x58, 0x14, 0xd3, 0x14, 0x0f,
	0x7f, 0x2d, 0x40, 0x4f, 0x6b, 0xae, 0x30, 0xcb, 0xe9, 0x35, 0x92, 0xb3, 0xbb, 0xc3, 0x6d, 0x57,
	0x0f, 0xe4, 0xe1, 0x66, 0x5a, 0xcf, 0x9a, 0x2f, 0x8b, 0x9d, 0x69, 0x91, 0x4f, 0xf5, 0x00, 0xc8,
	0x13, 0x5b, 0xef, 0xbe, 0x5d, 0xee, 0xbe, 0x7d, 0x22, 0x77, 0xdf, 0xaa, 0x97, 0x78, 0xb0, 0xb6,
	0x2d, 0x72, 0x0c, 0x66, 0xb5, 0x8f, 0xe4, 0x69, 0xc5, 0xbd, 0xbf, 0xcc, 0x96, 0xd5, 0x74, 0x55,
	0xb9, 0x7c, 0x84, 0x9e, 0x87, 0x41, 0x78, 0x25, 0x32, 0x0c, 0x12, 0xca, 0xa2, 0xb9, 0xdd, 0x6c,
	0x34, 0xbd, 0x81, 0xfd, 0xd6, 0xdb, 0xf6, 0xe0, 0x06, 0x36, 0xe5, 0x95, 0x1f, 0x62, 0x8e, 0x31,
	0x4f, 0x31, 0x1b, 0x97, 0xd4, 0x41, 0x57, 0x77, 0x7d, 0x29, 0xad, 0x2e, 0xdb, 0x5f, 0x8f, 0x22,
	0x2a, 0x46, 0x93, 0xa1, 0x7d, 0xcd, 0x13, 0x47, 0x52, 0xf6, 0x67, 0x12, 0x67, 0xc0, 0xcf, 0x4f,
	0xf7, 0x65, 0xd8, 0x98, 0x39, 0x11, 0x32, 0x55, 0xdd, 0x29, 0xbe, 0x99, 0xef, 0xe5, 0xef, 0xb0,
	0xa3, 0xb0, 0x77, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xdc, 0xc1, 0x48, 0x4a, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BattleServiceClient is the client API for BattleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BattleServiceClient interface {
	// ルームオーナーにのみ権限あり
	StartBattle(ctx context.Context, in *StartBattleRequest, opts ...grpc.CallOption) (*StartBattleResponse, error)
	// ルームオーナーにのみ権限あり
	StopBattle(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StopBattleResponse, error)
	// 撃たれたことを通知する
	// 「攻撃する/攻撃される」ロジックはこれで実装される
	NotifyHit(ctx context.Context, in *NotifyHitRequest, opts ...grpc.CallOption) (*NotifyHitResponse, error)
	// 自分がジョインしているルームで起きるイベント結果が
	// サーバーサイドストリーミングで返ってくる。
	ReadStreaming(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (BattleService_ReadStreamingClient, error)
}

type battleServiceClient struct {
	cc *grpc.ClientConn
}

func NewBattleServiceClient(cc *grpc.ClientConn) BattleServiceClient {
	return &battleServiceClient{cc}
}

func (c *battleServiceClient) StartBattle(ctx context.Context, in *StartBattleRequest, opts ...grpc.CallOption) (*StartBattleResponse, error) {
	out := new(StartBattleResponse)
	err := c.cc.Invoke(ctx, "/bolg.v1.BattleService/StartBattle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) StopBattle(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StopBattleResponse, error) {
	out := new(StopBattleResponse)
	err := c.cc.Invoke(ctx, "/bolg.v1.BattleService/StopBattle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) NotifyHit(ctx context.Context, in *NotifyHitRequest, opts ...grpc.CallOption) (*NotifyHitResponse, error) {
	out := new(NotifyHitResponse)
	err := c.cc.Invoke(ctx, "/bolg.v1.BattleService/NotifyHit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) ReadStreaming(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (BattleService_ReadStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BattleService_serviceDesc.Streams[0], "/bolg.v1.BattleService/ReadStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &battleServiceReadStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BattleService_ReadStreamingClient interface {
	Recv() (*EventResult, error)
	grpc.ClientStream
}

type battleServiceReadStreamingClient struct {
	grpc.ClientStream
}

func (x *battleServiceReadStreamingClient) Recv() (*EventResult, error) {
	m := new(EventResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BattleServiceServer is the server API for BattleService service.
type BattleServiceServer interface {
	// ルームオーナーにのみ権限あり
	StartBattle(context.Context, *StartBattleRequest) (*StartBattleResponse, error)
	// ルームオーナーにのみ権限あり
	StopBattle(context.Context, *empty.Empty) (*StopBattleResponse, error)
	// 撃たれたことを通知する
	// 「攻撃する/攻撃される」ロジックはこれで実装される
	NotifyHit(context.Context, *NotifyHitRequest) (*NotifyHitResponse, error)
	// 自分がジョインしているルームで起きるイベント結果が
	// サーバーサイドストリーミングで返ってくる。
	ReadStreaming(*empty.Empty, BattleService_ReadStreamingServer) error
}

func RegisterBattleServiceServer(s *grpc.Server, srv BattleServiceServer) {
	s.RegisterService(&_BattleService_serviceDesc, srv)
}

func _BattleService_StartBattle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBattleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).StartBattle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bolg.v1.BattleService/StartBattle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).StartBattle(ctx, req.(*StartBattleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_StopBattle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).StopBattle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bolg.v1.BattleService/StopBattle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).StopBattle(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_NotifyHit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyHitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).NotifyHit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bolg.v1.BattleService/NotifyHit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).NotifyHit(ctx, req.(*NotifyHitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_ReadStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BattleServiceServer).ReadStreaming(m, &battleServiceReadStreamingServer{stream})
}

type BattleService_ReadStreamingServer interface {
	Send(*EventResult) error
	grpc.ServerStream
}

type battleServiceReadStreamingServer struct {
	grpc.ServerStream
}

func (x *battleServiceReadStreamingServer) Send(m *EventResult) error {
	return x.ServerStream.SendMsg(m)
}

var _BattleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bolg.v1.BattleService",
	HandlerType: (*BattleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartBattle",
			Handler:    _BattleService_StartBattle_Handler,
		},
		{
			MethodName: "StopBattle",
			Handler:    _BattleService_StopBattle_Handler,
		},
		{
			MethodName: "NotifyHit",
			Handler:    _BattleService_NotifyHit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadStreaming",
			Handler:       _BattleService_ReadStreaming_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bolg/v1/battle.proto",
}
