// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bolg/v1/hello.proto

package bolg

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GreetResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetResponse) Reset()         { *m = GreetResponse{} }
func (m *GreetResponse) String() string { return proto.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()    {}
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba9cae5f7f609e4c, []int{0}
}

func (m *GreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResponse.Unmarshal(m, b)
}
func (m *GreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResponse.Marshal(b, m, deterministic)
}
func (m *GreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResponse.Merge(m, src)
}
func (m *GreetResponse) XXX_Size() int {
	return xxx_messageInfo_GreetResponse.Size(m)
}
func (m *GreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResponse proto.InternalMessageInfo

func (m *GreetResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GreetResponse)(nil), "bolg.v1.GreetResponse")
}

func init() { proto.RegisterFile("bolg/v1/hello.proto", fileDescriptor_ba9cae5f7f609e4c) }

var fileDescriptor_ba9cae5f7f609e4c = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4b, 0x43, 0x31,
	0x10, 0xc6, 0x7d, 0x43, 0x2d, 0x06, 0x5c, 0x9e, 0x50, 0x4b, 0x5d, 0xa4, 0x93, 0x0e, 0xbd, 0xa3,
	0x3a, 0x89, 0x4e, 0x01, 0xa9, 0x83, 0x43, 0xa9, 0x9b, 0x8b, 0x18, 0xfd, 0x4c, 0x85, 0xbc, 0x5e,
	0x48, 0xd2, 0x80, 0xff, 0xbd, 0x24, 0x7d, 0x0f, 0x71, 0x3a, 0xee, 0xbb, 0xef, 0xfb, 0x7d, 0x70,
	0xea, 0xcc, 0x88, 0xb3, 0x9c, 0x97, 0xbc, 0x85, 0x73, 0x42, 0x3e, 0x48, 0x92, 0x76, 0x5c, 0x44,
	0xca, 0xcb, 0xd9, 0x85, 0x15, 0xb1, 0x0e, 0x5c, 0x65, 0xb3, 0xff, 0x62, 0x74, 0x3e, 0xfd, 0x1c,
	0x5c, 0xf3, 0x6b, 0x75, 0xba, 0x0a, 0x40, 0xda, 0x20, 0x7a, 0xd9, 0x45, 0xb4, 0x53, 0x35, 0xee,
	0x10, 0xe3, 0xbb, 0xc5, 0xb4, 0xb9, 0x6c, 0xae, 0x4e, 0x36, 0xc3, 0x7a, 0xa3, 0xd5, 0xe8, 0xa9,
	0xf0, 0xdb, 0x3b, 0x35, 0xaa, 0x99, 0x76, 0x42, 0x07, 0x34, 0x0d, 0x68, 0x7a, 0x2c, 0xe8, 0xd9,
	0x84, 0xfa, 0x6e, 0xfa, 0xc7, 0x9e, 0x1f, 0x69, 0xa8, 0xf3, 0x72, 0x7a, 0xfb, 0x44, 0x86, 0x13,
	0x8f, 0x10, 0x07, 0xab, 0x56, 0x15, 0xbe, 0x2e, 0xa4, 0x75, 0xf3, 0xfa, 0x60, 0xbf, 0xd3, 0x76,
	0x6f, 0xe8, 0x43, 0x3a, 0x2e, 0x8e, 0xc5, 0x5f, 0x82, 0xb5, 0x3c, 0xaf, 0x16, 0x2f, 0x08, 0x19,
	0x81, 0x2d, 0x76, 0xb5, 0x9c, 0xfb, 0x17, 0xdc, 0x97, 0x69, 0x8e, 0xab, 0x76, 0xfb, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x5d, 0x93, 0xfa, 0xfb, 0x19, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	Greet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GreetResponse, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) Greet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/bolg.v1.Hello/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	Greet(context.Context, *empty.Empty) (*GreetResponse, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bolg.v1.Hello/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).Greet(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bolg.v1.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _Hello_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bolg/v1/hello.proto",
}
