// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bolg/v1/room.proto

package bolg

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Room struct {
	// uuid v4
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e1bc64bb6089cb, []int{0}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type JoinRoomRequest struct {
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// 既に使用されている名前を登録することはできない
	// 長さ: [1, 8]
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// マイコンから取得したIR-GUNの攻撃力
	// [1, 15]
	Power                int32    `protobuf:"varint,3,opt,name=power,proto3" json:"power,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomRequest) Reset()         { *m = JoinRoomRequest{} }
func (m *JoinRoomRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRoomRequest) ProtoMessage()    {}
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e1bc64bb6089cb, []int{1}
}

func (m *JoinRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomRequest.Unmarshal(m, b)
}
func (m *JoinRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomRequest.Marshal(b, m, deterministic)
}
func (m *JoinRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomRequest.Merge(m, src)
}
func (m *JoinRoomRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRoomRequest.Size(m)
}
func (m *JoinRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomRequest proto.InternalMessageInfo

func (m *JoinRoomRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *JoinRoomRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JoinRoomRequest) GetPower() int32 {
	if m != nil {
		return m.Power
	}
	return 0
}

type JoinRoomResponse struct {
	// 同じルーム参加しているすべてのプレイヤーのコレクション（自分も含む）
	Players []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	// RoomAuthServiceを利用するのに必要なアクセストークン。
	// どのルームにだれとしてアクセスしているのかを認可している。
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomResponse) Reset()         { *m = JoinRoomResponse{} }
func (m *JoinRoomResponse) String() string { return proto.CompactTextString(m) }
func (*JoinRoomResponse) ProtoMessage()    {}
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e1bc64bb6089cb, []int{2}
}

func (m *JoinRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomResponse.Unmarshal(m, b)
}
func (m *JoinRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomResponse.Marshal(b, m, deterministic)
}
func (m *JoinRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomResponse.Merge(m, src)
}
func (m *JoinRoomResponse) XXX_Size() int {
	return xxx_messageInfo_JoinRoomResponse.Size(m)
}
func (m *JoinRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomResponse proto.InternalMessageInfo

func (m *JoinRoomResponse) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *JoinRoomResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Player struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 初期値は0
	Hp                   int32    `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e1bc64bb6089cb, []int{3}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetHp() int32 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func init() {
	proto.RegisterType((*Room)(nil), "bolg.v1.Room")
	proto.RegisterType((*JoinRoomRequest)(nil), "bolg.v1.JoinRoomRequest")
	proto.RegisterType((*JoinRoomResponse)(nil), "bolg.v1.JoinRoomResponse")
	proto.RegisterType((*Player)(nil), "bolg.v1.Player")
}

func init() { proto.RegisterFile("bolg/v1/room.proto", fileDescriptor_98e1bc64bb6089cb) }

var fileDescriptor_98e1bc64bb6089cb = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xc5, 0xe6, 0xab, 0x0c, 0x2a, 0x54, 0xab, 0x0a, 0x5c, 0x7a, 0x41, 0x3e, 0x51, 0xa9, 0xec,
	0x0a, 0xaa, 0x9e, 0xda, 0x4b, 0xa9, 0xaa, 0x2a, 0x51, 0x0e, 0xc8, 0xe4, 0x94, 0x0b, 0xc2, 0x78,
	0x62, 0xac, 0xd8, 0x9e, 0xcd, 0xda, 0x38, 0xe2, 0x17, 0xe4, 0x6f, 0x47, 0xbb, 0xc6, 0x26, 0x8a,
	0x72, 0xb2, 0xe7, 0xbd, 0x37, 0x33, 0x6f, 0x9e, 0x16, 0x98, 0x4f, 0x71, 0x28, 0x8a, 0x85, 0x50,
	0x44, 0x09, 0x97, 0x8a, 0x72, 0x62, 0x5d, 0x8d, 0xf1, 0x62, 0x31, 0xf9, 0x1a, 0x12, 0x85, 0x31,
	0x0a, 0x03, 0xfb, 0xc7, 0x7b, 0x81, 0x89, 0xcc, 0x4f, 0xa5, 0xca, 0x1d, 0x41, 0xcb, 0x23, 0x4a,
	0xd8, 0x00, 0xec, 0x28, 0x70, 0xac, 0xa9, 0x35, 0xeb, 0x79, 0x76, 0x14, 0xb8, 0xb7, 0x30, 0xbc,
	0xa6, 0x28, 0xd5, 0x9c, 0x87, 0x8f, 0x47, 0xcc, 0x72, 0x36, 0x86, 0xae, 0x1e, 0xbf, 0xad, 0x75,
	0x1d, 0x5d, 0x5e, 0x05, 0x8c, 0x41, 0x2b, 0xdd, 0x25, 0xe8, 0xd8, 0x06, 0x35, 0xff, 0xec, 0x33,
	0xb4, 0x25, 0x3d, 0xa1, 0x72, 0x9a, 0x53, 0x6b, 0xd6, 0xf6, 0xca, 0xc2, 0xdd, 0xc0, 0xa7, 0xcb,
	0xd4, 0x4c, 0x52, 0x9a, 0x21, 0xfb, 0x06, 0x5d, 0x19, 0xef, 0x4e, 0xa8, 0x32, 0xc7, 0x9a, 0x36,
	0x67, 0xfd, 0xe5, 0x90, 0x9f, 0x9d, 0xf3, 0xb5, 0xc1, 0xbd, 0x8a, 0xd7, 0x43, 0x73, 0x7a, 0xc0,
	0xf4, 0xbc, 0xa9, 0x2c, 0xdc, 0xef, 0xd0, 0x29, 0x85, 0xb5, 0x11, 0xeb, 0x95, 0x91, 0x01, 0xd8,
	0x07, 0x69, 0x1a, 0xda, 0x9e, 0x7d, 0x90, 0xcb, 0x67, 0x0b, 0xfa, 0x7a, 0xff, 0x06, 0x55, 0x11,
	0xed, 0x91, 0xfd, 0x04, 0xf8, 0xab, 0x70, 0x97, 0xa3, 0x89, 0x61, 0xc4, 0xcb, 0xb0, 0x78, 0x15,
	0x16, 0xff, 0xa7, 0xc3, 0x9a, 0x7c, 0xac, 0x3d, 0x69, 0x99, 0xdb, 0x60, 0x7f, 0xe0, 0x43, 0x75,
	0x09, 0x73, 0x6a, 0xf2, 0x4d, 0x64, 0x93, 0x2f, 0xef, 0x30, 0xe5, 0xd9, 0x6e, 0x63, 0x15, 0xc0,
	0x58, 0xb3, 0xdb, 0x00, 0x0b, 0x8c, 0x49, 0xa2, 0xca, 0x2a, 0xf5, 0xaa, 0xa7, 0xa5, 0x6b, 0x6d,
	0x61, 0x6d, 0xdd, 0xfd, 0x0e, 0xa3, 0xfc, 0x70, 0xf4, 0xf9, 0x9e, 0x12, 0xa1, 0x05, 0xf3, 0x4b,
	0x83, 0x58, 0xd1, 0xcd, 0xff, 0xb9, 0x3e, 0x05, 0x95, 0x08, 0x31, 0x35, 0xae, 0xc5, 0xf9, 0x31,
	0xfc, 0xd2, 0x5f, 0xbf, 0x63, 0xb0, 0x1f, 0x2f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x32, 0xc7,
	0x11, 0x23, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoomServiceClient is the client API for RoomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoomServiceClient interface {
	CreateRoom(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Room, error)
	JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error)
}

type roomServiceClient struct {
	cc *grpc.ClientConn
}

func NewRoomServiceClient(cc *grpc.ClientConn) RoomServiceClient {
	return &roomServiceClient{cc}
}

func (c *roomServiceClient) CreateRoom(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/bolg.v1.RoomService/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error) {
	out := new(JoinRoomResponse)
	err := c.cc.Invoke(ctx, "/bolg.v1.RoomService/JoinRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomServiceServer is the server API for RoomService service.
type RoomServiceServer interface {
	CreateRoom(context.Context, *empty.Empty) (*Room, error)
	JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error)
}

func RegisterRoomServiceServer(s *grpc.Server, srv RoomServiceServer) {
	s.RegisterService(&_RoomService_serviceDesc, srv)
}

func _RoomService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bolg.v1.RoomService/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).CreateRoom(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bolg.v1.RoomService/JoinRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).JoinRoom(ctx, req.(*JoinRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoomService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bolg.v1.RoomService",
	HandlerType: (*RoomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _RoomService_CreateRoom_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _RoomService_JoinRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bolg/v1/room.proto",
}
